// // frontend/src/components/ResultCard.jsx
// import React, { useEffect } from "react";

// export default function ResultCard({ result }) {
//   if (!result) return null;

//   // 🧩 Destructure correctly matched fields from backend
//   const {
//     predicted_disease,
//     description,
//     precautions = [],
//     medications = [],
//     diet = [],
//     workout = [],
//   } = result;

//   // 🧠 Debugging (to confirm data flow)
//   useEffect(() => {
//     console.log("✅ AI Result Received:", result);
//   }, [result]);

//   return (
//     <div className="border p-4 rounded-lg shadow-lg mt-6 bg-white">
//       {/* Disease Title */}
//       <h2 className="text-xl font-bold mb-2 text-blue-600">
//         {predicted_disease || "No disease predicted"}
//       </h2>

//       {/* Description */}
//       <p className="mb-2 text-gray-700">
//         {description || "No description available."}
//       </p>

//       {/* Precautions */}
//       <div className="mb-3">
//         <h3 className="font-semibold">Precautions:</h3>
//         <ul className="list-disc list-inside text-gray-700">
//           {precautions.length > 0 ? (
//             precautions.map((p, i) => <li key={i}>{p}</li>)
//           ) : (
//             <li>No precautions available.</li>
//           )}
//         </ul>
//       </div>

//       {/* Medications */}
//       <div className="mb-3">
//         <h3 className="font-semibold">Medications:</h3>
//         <ul className="list-disc list-inside text-gray-700">
//           {medications.length > 0 ? (
//             medications.map((m, i) => <li key={i}>{m}</li>)
//           ) : (
//             <li>No medications available.</li>
//           )}
//         </ul>
//       </div>

//       {/* Diet */}
//       <div className="mb-3">
//         <h3 className="font-semibold">Diet:</h3>
//         <ul className="list-disc list-inside text-gray-700">
//           {diet.length > 0 ? (
//             diet.map((d, i) => <li key={i}>{d}</li>)
//           ) : (
//             <li>No diet suggestions available.</li>
//           )}
//         </ul>
//       </div>

//       {/* Workout */}
//       <div>
//         <h3 className="font-semibold">Workout:</h3>
//         {workout.length > 0 ? (
//           <ul className="list-disc list-inside text-gray-700">
//             {workout.map((w, i) => (
//               <li key={i}>{w}</li>
//             ))}
//           </ul>
//         ) : (
//           <p>No workout advice available.</p>
//         )}
//       </div>
//     </div>
//   );
// }

import React, { useEffect } from "react";
import {
  ShieldCheck,
  Pill,
  Apple,
  Dumbbell,
  Activity,
  BrainCircuit,
} from "lucide-react";

export default function ResultCard({ result }) {
  if (!result) return null;

  const {
    predicted_disease,
    description,
    precautions = [],
    medications = [],
    diet = [],
    workout = [],
  } = result;

  useEffect(() => {
    console.log("🧠 AI Result Received:", result);
  }, [result]);

  return (
    <div className="relative border border-blue-100 p-10 rounded-3xl shadow-2xl mt-10 bg-gradient-to-br from-white/80 to-blue-50/50 backdrop-blur-lg overflow-hidden animate-fade-in">
      {/* ✨ Glowing border animation */}
      <div className="absolute inset-0 rounded-3xl border-2 border-transparent bg-gradient-to-r from-blue-500 via-teal-400 to-purple-500 animate-borderGlow -z-10"></div>

      {/* 🧠 Header */}
      <div className="text-center mb-8">
        <div className="flex justify-center mb-3">
          <div className="bg-gradient-to-r from-blue-500 to-teal-400 p-3 rounded-full shadow-md">
            <BrainCircuit size={32} className="text-white" />
          </div>
        </div>
        <h2 className="text-3xl font-extrabold bg-gradient-to-r from-blue-700 to-teal-500 bg-clip-text text-transparent">
          AI Health Intelligence Report
        </h2>
        <p className="text-gray-600 mt-2 text-sm">
          Generated by our advanced AI model, analyzing your selected symptoms.
        </p>
      </div>

      {/* 🩺 Disease Overview */}
      <div className="text-center mb-10">
        <h3 className="text-2xl font-semibold text-gray-800 tracking-wide">
          {predicted_disease || "No disease predicted"}
        </h3>
        <p className="mt-3 text-gray-600 italic leading-relaxed max-w-2xl mx-auto">
          {description || "No description available."}
        </p>
        <div className="w-28 h-1 mx-auto mt-4 bg-gradient-to-r from-blue-500 to-teal-400 rounded-full"></div>
      </div>

      {/* 🧩 AI Recommendations Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Precautions */}
        <InfoCard
          title="Precautions"
          color="pink"
          icon={<ShieldCheck size={22} />}
          items={precautions}
        />

        {/* Medications */}
        <InfoCard
          title="Medications"
          color="red"
          icon={<Pill size={22} />}
          items={medications}
        />

        {/* Diet */}
        <InfoCard
          title="Diet"
          color="yellow"
          icon={<Apple size={22} />}
          items={diet}
        />

        {/* Workout */}
        <InfoCard
          title="Workout"
          color="green"
          icon={<Dumbbell size={22} />}
          items={workout}
        />
      </div>

      {/* Footer */}
      <div className="text-center text-xs text-gray-500 mt-10 flex justify-center items-center gap-2">
        <Activity size={14} className="text-blue-500" />
        This AI report is for educational and guidance purposes only.
      </div>

      {/* 🌈 Animations */}
      <style>
        {`
          @keyframes borderGlow {
            0% { opacity: 0.3; filter: hue-rotate(0deg); }
            50% { opacity: 0.8; filter: hue-rotate(90deg); }
            100% { opacity: 0.3; filter: hue-rotate(360deg); }
          }
          .animate-borderGlow {
            animation: borderGlow 8s linear infinite;
          }
          @keyframes fade-in {
            from { opacity: 0; transform: translateY(10px); }
            to { opacity: 1; transform: translateY(0); }
          }
          .animate-fade-in {
            animation: fade-in 0.8s ease-in-out;
          }
        `}
      </style>
    </div>
  );
}

/* 🧠 Reusable InfoCard Component */
function InfoCard({ title, color, icon, items }) {
  const colorMap = {
    pink: "from-pink-50 to-pink-100 border-pink-200 text-pink-600",
    red: "from-red-50 to-red-100 border-red-200 text-red-600",
    yellow: "from-yellow-50 to-yellow-100 border-yellow-200 text-yellow-600",
    green: "from-green-50 to-green-100 border-green-200 text-green-600",
  };

  return (
    <div
      className={`p-5 rounded-2xl border shadow-sm hover:shadow-lg transition transform hover:-translate-y-1 bg-gradient-to-b ${colorMap[color]} duration-300`}
    >
      <div className="flex items-center gap-2 mb-3">
        <div
          className={`p-2 rounded-full bg-gradient-to-r ${colorMap[
            color
          ].replace("border-", "")} bg-opacity-20`}
        >
          {icon}
        </div>
        <h3 className="font-semibold text-lg">{title}</h3>
      </div>
      <ul className="list-disc list-inside text-gray-700 text-sm space-y-1">
        {items.length ? (
          items.map((item, i) => <li key={i}>{item}</li>)
        ) : (
          <li>No {title.toLowerCase()} available.</li>
        )}
      </ul>
    </div>
  );
}
